{
    "button":[
        {
            "name":"练剑",
            "sub_button":[
                {
                    "type":"click",
                    "name":"昨晚睡眠很好",
                    "key":"sleep"
                },
                {
                    "type":"click",
                    "name":"今天心情很好",
                    "key":"happy"
                },
                {
                    "type":"click",
                    "name":"学习半小时",
                    "key":"learning"
                },
                {
                    "type":"click",
                    "name":"运动半小时",
                    "key":"sport"
                },
                {
                    "type":"click",
                    "name":"陪家人半小时",
                    "key":"family"
                }
            ]
        },
        { 
            "type":"click",
            "name":"比武",
            "key":"challenge"
        },
        {
            "type":"click",
            "name":"关于",
            "key":"about"
        }
    ]
}
